### ISSUE TITLE
rate of change

### ISSUE THREAD

**Issue by pedramp** [mohsentaleb/chande#3]
- Adding a simple icon (`↑↓`) beside the currency to show the change direction, based on the previous price. 

Sample: 
![Screen Shot 2019-10-09 at 15 16 58](https://user-images.githubusercontent.com/202137/66480673-dc6bc880-eaa7-11e9-8dc1-936c25f66b7c.png)

**Comment by mohsentaleb** [comment]
It's resolved in commit bec14001fc3d44e219d5efcc434e7c8e95aa9ab9 .
