### ISSUE TITLE
unit testing

### ISSUE THREAD

**Issue by pedramp** [mohsentaleb/chande#4]
_unit test_ implementation needed.

**Comment by mohsentaleb** [comment]
@pedramp Shall I assign it to you?

**Comment by pedramp** [comment]
Sure :)

**Comment by mohsentaleb** [comment]
@pedramp I'm setting it up with [Jest](https://jestjs.io). Hope that's ok with you.

**Comment by pedramp** [comment]
yup, why not 👍
