### ISSUE TITLE
colorizing idea

### ISSUE THREAD

**Issue by pedramp** [mohsentaleb/chande#5]
ideas: 
- using [Colors](https://github.com/Marak/colors.js) package to colorize arrows (red/green) 
- even/odd rows color change (maybe white and light-gray) 

`chande` is a very lightweight package, and maybe it is not a good idea to add different packages just for simple UI functionalities, but on the other hand, colorization is not a bad idea :D  anyway I want to share my idea!

**Comment by mohsentaleb** [comment]
Honestly, in version `1.0.0` I was using [Chalk](https://www.npmjs.com/package/chalk) for painting items in the table, and then I removed it due to the same reason you truly mentioned, simplicity. Let's try it one more time and see what happens :)
Thanks Pedy.

**Comment by mohsentaleb** [comment]
Since price fluctuations are dismissed in the most recent update, the whole purpose of issue is now irrelevant. Closing it..
